customhost = "employee.cdejvo6oxbk1.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "jeffreychowsaiwai-employee"
customregion = "us-east-1"
